### PR TITLE
2023-1.0 envs

### LINKED ISSUE #8: Add `pymcr` to the collection and collection-tiled envs
- https://anaconda.org/conda-forge/pymcr
- https://pypi.org/project/pyMCR

Needed at ISS in the analysis profile.

### LINKED ISSUE #10: Add `pymca` package
Requested by BMM.

https://anaconda.org/conda-forge/pymca/files

### PR DESCRIPTION
**Pull request by mrakitin**
The environments are to be deployed during the January 2023 shutdown.

Diffs:

```diff
$ diff envs/env-py39.yml envs/env-py310.yml
1c1
< name: 2023-1.0-py39
---
> name: 2023-1.0-py310
10c10
<   - python >=3.9,<3.10
---
>   - python >=3.10,<3.11
```

```diff
$ diff configs/config-py39.yml configs/config-py310.yml
2,3c2,3
< env_name: "2023-1.0-py39"
< conda_env_file: "env-py39.yml"
---
> env_name: "2023-1.0-py310"
> conda_env_file: "env-py310.yml"
5c5
< python_version: "3.9"
---
> python_version: "3.10"
```

### CODE REVIEW

**Comment by mrakitin** [comment]
@jklynch, @tacaswell, could you please review?

**Comment by mrakitin** [comment]
Need to address #10 and #8.

**Comment by mrakitin** [comment]
Ready for review!

**Review by tacaswell — APPROVED** [review]

**Comment by maffettone** [comment]
Very pleased about the torch and pymca additions. Have we checked with @dmgav that the combined versions of `bluesky-queueserver`, `bluesky-queueserver-api` are the commensurate versions? I know these have been under rapid dev (and are very useful to some ongoing projects).

**Comment by mrakitin** [comment]
> Very pleased about the torch and pymca additions.

My pleasure! They were planned for a long time, so finally were added.

> Have we checked with @dmgav that the combined versions of bluesky-queueserver, bluesky-queueserver-api are the commensurate versions? I know these have been under rapid dev (and are very useful to some ongoing projects).

Those libraries have minimum pins: 

```yaml
  - bluesky-queueserver >=0.0.18
  - bluesky-queueserver-api >=0.0.9
```

so conda will pick ~latest versions, but if @dmgav has any specific preference for the minimum versions, I'll be happy to add them here too.

**Comment by dmgav** [comment]
I would recommend using the latest versions of `bluesky-queueserver` and `bluesky-queueserver-api`. They should still work with Python 3.7 if it is needed, unit tests are not working with Python 3.7 though. Same with `bluesky-widgets`.

**Comment by mrakitin** [comment]
Just FYI, we got rid of Python 3.7 and 3.8 recently, and plan to deploy 2 versions - with Python 3.9 and 3.10 (new this cycle!)

For the versions:
- https://github.com/conda-forge/bluesky-queueserver-feedstock/blob/2248214a95b07f8fbd525345754213834cd211b2/recipe/meta.yaml#L2 lists the version I specified here (v0.0.18)
- https://github.com/conda-forge/bluesky-queueserver-api-feedstock/blob/1ae3758d420751ba541d6a4286cb2b8edbbee825/recipe/meta.yaml#L2 lists the version I specified here (v0.0.9)

**Comment by mrakitin** [comment]
Thanks for your reviews, I'll merge both PRs then.

**Comment by mrakitin** [comment]
Deposited to https://zenodo.org/record/7470912 via https://github.com/nsls2-conda-envs/playground/actions/runs/3753798831/jobs/6377399827.

**Pull request merged**
