### PR TITLE
2022-3.1

### PR DESCRIPTION
**Pull request by gwbischof**
We suspect that the python 3.8 environments are no longer needed.

### CODE REVIEW

**Comment by gwbischof** [comment]
Expecting this to fail until xpdacq 1.1.0 is released.

**Review by mrakitin — APPROVED** [review]
Looks good to me. Probably we should comment out the `py38` builds in the workflow to skip the build and just generate a single environment for Python 3.9. Thoughts?

**Review by mrakitin — APPROVED** [review]
Looks good to me. Let's wait for the CI to succeed before merging.

**Comment by mrakitin** [comment]
I checked the contents of the resulting .yml file in https://github.com/nsls2-conda-envs/nsls2-collection/runs/8137656156?check_suite_focus=true, looks good.

**Pull request merged**
